[package]
  categories = ["development-tools", "development-tools::linters"]
  description = "An opinionated formatting and linting tool for foundry projects"
  edition = "2021"
  keywords = ["foundry", "linting", "formatting"]
  license = "MIT"
  name = "scopelint"
  repository = "https://github.com/ScopeLift/scopelint"
  version = "0.0.12"

[dependencies]
  colored = "2.0.0"
  once_cell = "1.16.0"
  regex = "1.6.0"
  solang-parser = "0.1.18"
  taplo = "0.11.0"
  walkdir = "2.3.2"
