[package]
  categories = ["development-tools", "development-tools::linters"]
  description = "An opinionated formatting and linting tool for foundry projects"
  edition = "2021"
  keywords = ["foundry", "linting", "formatting"]
  license = "MIT"
  name = "scopelint"
  repository = "https://github.com/ScopeLift/scopelint"
  version = "0.0.10"

[dependencies]
  grep = "0.2.10"
  regex = "1.6.0"
  taplo = "0.11.0"
  walkdir = "2.3.2"
