[package]
  description = "An opinionated formatting and linting tool for foundry projects"
  edition = "2021"
  license = "MIT"
  name = "scopelint"
  repository = "https://github.com/ScopeLift/scopelint"
  version = "0.0.8"

[dependencies]
  grep = "0.2.10"
  regex = "1.6.0"
  taplo = "0.11.0"
  walkdir = "2.3.2"
