[package]
  description = "An opinionated formatting and linting tool for foundry projects"
  edition = "2021"
  license = "MIT"
  name = "scopelint"
  repository = "https://github.com/ScopeLift/scopelint"
  version = "0.0.1"

[dependencies]
  taplo = "0.11.0"
